version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    networks:
      - sqlserver-network
    volumes:
      - ./sqlserver-data:/var/opt/mssql
    env_file:
      - .env

networks:
  sqlserver-network:
    driver: bridge

volumes:
  sqlserver-data:
